### PR TITLE
Add ability to remove old backups

### PR DESCRIPTION
**Pull request by michael-misshore**

### CODE REVIEW

**Comment by alexdebrie** [comment]
Awesome! Thanks, @michael-misshore. At a first glance, this looks great but I'll take a closer look in the next day or two. 😄 

Can you add some documentation notes in the README as well?

**Comment by michael-misshore** [comment]
@alexdebrie, It's my pleasure and no rush!

I'll go ahead and add some documentation in the next couple of days. Likewise, is there anything I can do to contribute towards testing?

**Comment by alexdebrie** [comment]
@michael-misshore The code looks good to me. Two outstanding issues from me:

1) Updating the documentation to reflect this new functionality & configuration.

2) How to handle this for users that *don't* want to remove old backups? I see a few options:

* Users can set a really large number for `BACKUP_RETENTION_DAYS` (e.g., `1000000`). This doesn't require any code change, just documentation.

* Certain values of `BACKUP_RETENTION_DAYS` indicate that backups shouldn't be deleted -- e.g. "0" or "-1". Does require a code change.

* Have another environment variable (`BACKUP_REMOVAL_ENABLED`) which users can set to `False` to avoid removing old backups. Requires a code change.


Any preference on those options or thoughts on another option?

**Comment by michael-misshore** [comment]
@alexdebrie While I don't want to litter the plugin with more flags than we need, I do like the 3rd option you mentioned regarding users who do not want to remove old backups.

I can add this along with the necessary documentation.

**Comment by michael-misshore** [comment]
@alexdebrie discussed changes have been pushed

**Comment by alexdebrie** [comment]
@michael-misshore I like your suggestion, and the code looks good to me!

One small request before I merge -- in the [example](https://github.com/michael-misshore/serverless-dynamodb-backups/blob/4e0b3ac657f9c774be02269b641b93d4de67f9de/serverless.yml#L9), can you set `backupRemovalEnabled` to `true`? Since we're including the retention time in the example, we might as well enable it as well.

Once that's done, I'll merge it. Thanks for adding this!

**Comment by michael-misshore** [comment]
@alexdebrie, This is complete.

It's my pleasure!

**Pull request merged**
